name: Deploy web app to Azure Static Web Apps
# Environment variables
env:
  APP_LOCATION: "/" # location of your client code
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
# Permissions
permissions:
  issues: write
  contents: read
# Jobs
jobs:
  build_and_deploy:
    # Run when there is a push to main or a pull request to main that is open, synchronized, reopened, or closed
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
      # Build and deploy the app
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.STATIC_WEB_CONFIG_PACFILE }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
  close:
    # Run when a pull request to main is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close
    steps:
      # Close the pull request
      - name: Close
        run: echo ${{ toJson(github.event.pull_request) }}